### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by wanglihui2233** [chengshuyi/tjutPyLucene#1]
1.页面重要度算法使用的是三个主流算法中的哪个？
2.中文分词使用的是三大类中的哪个？
3.tf-idf算法是判断词的重要性找出文章的关键词，我这系统有用到吗？
4.djiango用来干嘛了？搭配nginx使用了吗？
5.这个系统是不是B/S模式的，搜索引擎是只能在我的电脑上用吗？

**Comment by chengshuyi** [comment]
1. 哪三个主流算法？
2. 哪三大类？我用的是lucene自带的中文分词。
3. lucene自带tf-id，这也是lucene的核心之一。
4. django不就是web框架吗？想用的话，可以搭配nginx。只是做毕设的话，没有必要真的搞个服务器。不过你可以在论文里面提到。
5. 肯定的啊，除非你自己买一台服务器【如果你觉得这个对你很重要的话】。
